worker_processes auto;
daemon off;
error_log /tmp/pgo-run/logs/error.log;
pid /tmp/pgo-run/nginx.pid;

events {
    worker_connections 2048;
}

stream {
    # 训练 Stream 版本的 GeoIP2 模块
    geoip2 /tmp/pgo-run/geoip/GeoLite2-Country.mmdb {
        $geoip2_data_country_code_stream country iso_code;
    }
	map $ssl_preread_server_name $backend {
        example.com  127.0.0.1:8081; 
        default      127.0.0.1:8082; 
    }
    server {
        listen 8443;
        proxy_pass $backend;
        ssl_preread on;
    }
}

http {
    # 路径必须与 Stage 2 脚本中 mkdir 的路径严格一致
    client_body_temp_path /tmp/pgo-run/client_body_temp;
    proxy_temp_path       /tmp/pgo-run/proxy_temp;
    fastcgi_temp_path     /tmp/pgo-run/fastcgi_temp;
    uwsgi_temp_path       /tmp/pgo-run/uwsgi_temp;
    scgi_temp_path        /tmp/pgo-run/scgi_temp;

    geoip2 /tmp/pgo-run/geoip/GeoLite2-Country.mmdb { $geoip2_data_country_code country iso_code; }
    
	# 补全 WebSocket 变量定义
    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }
    
    server {
        listen 8081 ; # 关键：必须开启 http2 才能训练 gRPC 模块
        http2 on;
		add_header X-IP-Country $geoip2_data_country_code;

        # 1. 真正的 gRPC 转发逻辑 (训练 ngx_http_grpc_module)
        location /helloworld.Greeter/SayHello {
            grpc_pass grpc://127.0.0.1:50051; 
        }

        # 2. WebSocket 逻辑
        location /ws {
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            # 即使后端不存在，握手逻辑也能被训练
            proxy_pass http://127.0.0.1:8082; 
        }

        # 3. 默认兜底
        location / {
            return 200 "PGO training content";
        }
    }

    # 模拟一个后端，防止转发报错导致 Nginx 过早关闭连接
    server {
        listen 8082;
        location / { return 200 "backend_ok"; }
    }
}
