worker_processes auto;
daemon off;
error_log /tmp/pgo-run/logs/error.log;
pid /tmp/pgo-run/nginx.pid;

events {
    worker_connections 2048;
}

stream {
    map $ssl_preread_server_name $backend {
        example.com  127.0.0.1:8081; 
        default      127.0.0.1:8082; 
    }
    server {
        listen 8443;
        proxy_pass $backend;
        ssl_preread on;
    }
}

http {
    # 路径必须与 Stage 2 脚本中 mkdir 的路径严格一致
    client_body_temp_path /tmp/pgo-run/client_body_temp;
    proxy_temp_path       /tmp/pgo-run/proxy_temp;
    fastcgi_temp_path     /tmp/pgo-run/fastcgi_temp;
    uwsgi_temp_path       /tmp/pgo-run/uwsgi_temp;
    scgi_temp_path        /tmp/pgo-run/scgi_temp;

    geoip2 /tmp/pgo-run/geoip/GeoLite2-Country.mmdb { $geoip2_data_country_code country iso_code; }
    
    
    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }
     
    server {
        listen 8081;
        add_header X-IP-Country $geoip2_data_country_code;
       
        
        location /ws { return 200 "ws_ok"; }
        location /grpc { return 200 "grpc_ok"; }
        location / { return 200 "PGO training content"; }
    }
}
